---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown
repo: cscb-template

### content configuration ###
title:       "Center for Stem Cell Bioinformatics | HMS DBMI"
keywords:    "Harvard, Medical, School, university, stem cell, bioinformatics"
description: "A single-page template for Jekyll based blogs (like what you'd use on github pages!)"
source_link: "https://github.com/t413/SinglePaged"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)
top_nav_color_default: '#24a5ff'
blur_nav_color_bar : false


### Pre-defined template color 'shortcuts', use in SinglePaged page/section page headers
### Or, may use hex representation directly (if want to use different color)
colors:
  black:        '#111111'
  white:        '#f8f8f8'
  blue:         '#49a7e9'
  bluedark:     '#3892d2'
  bluebrighter: '#24a5ff'
  green:        '#9bcf2f'
  purple:       '#c869bf'
  orange:       '#fab125'
  turquoise:    '#0fbfcf'
  harvardred:   '#c4162d'
  4dnblue:      '#258cab'
  4dngreen:     '#80a847'


kramdown:
  auto_ids:  false

### Setup SinglePaged pages comprised of collections' sections.
### Required meta-fields: 
###   order (order to appear in top nav)
### Optional meta-fields : 
###   color (for top nav border), otherwise will be empty and top_nav_active_color will be set when active
###   title (in case has spaces (not supported by label))
collections:
  home:
    order: 0
    color: bluebrighter
  stem-cell-commons:
    order: 1 
    title: "Stem Cell Commons"
    color: bluebrighter
  about:
    order: 2
    color: bluedark
  training:
    order: 3
    color: green
  consulting:
    order: 4
    color: turquoise
  #team:
  #  order: 5
  #  color: turquoise

team_members:

  - name: "Nils Gehlenborg"
    avatar: http://static.projects.iq.harvard.edu/files/styles/profile_full/public/parklab/files/nils_gehlenborg_march2011-3.png?m=1445310749&itok=DH-IqGUU
    email: text@example.com
    link: http://www.gehlenborg.com/
    role: "Principal Investigator (PI)"
    more_info: "Gehlenborg Lab" # Use 'more_info' for any extra info, shown under role on 'card'

  - name: "Peter Park"
    role : "Principal Investigator (PI)"
    avatar: http://static.projects.iq.harvard.edu/files/styles/profile_full/public/parklab/files/pjp_portrait432x288.jpg?m=1445270272&itok=MCx1LyYW
    link: http://compbio.hms.harvard.edu/people/peter-j-parklab
    more_info: '<a href="http://compbio.hms.harvard.edu/" target="_blank">Park Lab</a>'

  - name: "Jennifer Marx"
    role : "Software Engineer"
    avatar: http://static.projects.iq.harvard.edu/files/styles/profile_full/public/parklab/files/circular_jm_2.jpeg?m=1445288985&itok=xPrw5QKe
    link: http://www.jkmarx.com/
    more_info: '<a href="http://compbio.hms.harvard.edu/" target="_blank">Park Lab</a>'

  - name: "Scott Ouellette"
    role : "Software Engineer"
    avatar: http://static.projects.iq.harvard.edu/files/styles/profile_full/public/parklab/files/scottouellette_0.jpeg?m=1445275612&itok=K51ECKii
    link: http://www.scott-ouellette.com/
    more_info: '<a href="http://compbio.hms.harvard.edu/" target="_blank">Park Lab</a>'

team_members_config:
  group_by_role: false
  show_emails: false

layout:
  divider_size: 100 # Increase or decrease size of section dividers