---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown
repo: cscb-template

### content configuration ###
title:       "Center for Stem Cell Bioinformatics | HMS DBMI"
keywords:    "Harvard, Medical, School, university, stem cell, bioinformatics"
description: "A single-page template for Jekyll based blogs (like what you'd use on github pages!)"
source_link: "https://github.com/t413/SinglePaged"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)
top_nav_color_default: '#24a5ff'


### Pre-defined template color 'shortcuts', use in SinglePaged page/section page headers
### Or, may use hex representation directly (if want to use different color)
colors:
  black:        '#111111'
  white:        '#f8f8f8'
  blue:         '#49a7e9'
  bluedark:     '#3892d2'
  bluebrighter: '#24a5ff'
  green:        '#9bcf2f'
  purple:       '#c869bf'
  orange:       '#fab125'
  turquoise:    '#0fbfcf'

kramdown:
  auto_ids:  false

### Setup SinglePaged pages comprised of collections' sections.
### Required meta-fields: 
###   order (order to appear in top nav)
### Optional meta-fields : 
###   color (for top nav border), otherwise will be empty and top_nav_active_color will be set when active
###   title (in case has spaces (not supported by label))
collections:
  home:
    order: 0
    color: bluedark
  about:
    order: 1
    color: purple
  stem-cell-commons:
    order: 2 
    title: "Stem Cell Commons"
    color: bluebrighter
  training:
    order: 3
    color: green
  consulting:
    order: 4
    color: turquoise
  #team:
  #  order: 5
  #  color: turquoise