---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown
repo: cscb-template

### content configuration ###
title:       "Center for Stem Cell Bioinformatics | HMS DBMI"
keywords:    "Harvard, Medical, School, university, stem cell, bioinformatics"
description: "A single-page template for Jekyll based blogs (like what you'd use on github pages!)"
source_link: "https://github.com/t413/SinglePaged"
favicon:     "img/hms-favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)
top_nav_color_default: '#24a5ff'
blur_nav_color_bar : false


### Pre-defined template color 'shortcuts', use in SinglePaged page/section page headers
### Or, may use hex representation directly (if want to use different color)
colors:

  # Default SinglePaged colors
  black:          '#111111'
  white:          '#f8f8f8'
  blue:           '#49a7e9'
  green:          '#9bcf2f'
  purple:         '#c869bf'
  orange:         '#fab125'
  turquoise:      '#0fbfcf'

  # HMS Colors
  harvardcrimson: '#c4162d'
  brightblue:     '#24a5ff'
  darkblue:       '#1f8cd9'
  4dnblue:        '#258cab'
  4dngreen:       '#80a847'
  bluedark:       '#3892d2'
  bluebrighter:   '#24a5ff'


kramdown:
  auto_ids:  false

### Setup SinglePaged pages comprised of collections' sections.
### Required meta-fields: 
###   order (order to appear in top nav)
### Optional meta-fields : 
###   color (for top nav border), otherwise will be empty and top_nav_active_color will be set when active
###   title (in case has spaces (not supported by label))
collections:
  home:
    order: 0
    color: brightblue
  about:
    order: 1
    color: darkblue
  training:
    order: 2
    color: brightblue
  consulting:
    order: 3
    color: darkblue
  stem-cell-commons:
    order: 4 
    title: "Stem Cell Commons"
    color: brightblue

team_members:
    # If possible, use '//' or 'https://' instead of 'http://' for avatars
  - name: "Nils Gehlenborg"
    avatar: //static.projects.iq.harvard.edu/files/styles/profile_full/public/parklab/files/nils_gehlenborg_march2011-3.png?m=1445310749&itok=DH-IqGUU
    email: text@example.com
    link: http://www.gehlenborg.com/
    role: "Principal Investigator (PI)"
    more_info: "Gehlenborg Lab" # Use 'more_info' for any extra info, shown under role on 'card'

  - name: "Peter Park"
    role : "Principal Investigator (PI)"
    avatar: //static.projects.iq.harvard.edu/files/styles/profile_full/public/parklab/files/pjp_portrait432x288.jpg?m=1445270272&itok=MCx1LyYW
    link: http://compbio.hms.harvard.edu/people/peter-j-parklab
    more_info: '<a href="http://compbio.hms.harvard.edu/" target="_blank">Park Lab</a>'

  - name: "Jennifer Marx"
    role : "Software Engineer"
    avatar: //static.projects.iq.harvard.edu/files/styles/profile_full/public/parklab/files/circular_jm_2.jpeg?m=1445288985&itok=xPrw5QKe
    link: http://www.jkmarx.com/
    more_info: '<a href="http://compbio.hms.harvard.edu/" target="_blank">Park Lab</a>'

  - name: "Scott Ouellette"
    role : "Software Engineer"
    avatar: //static.projects.iq.harvard.edu/files/styles/profile_full/public/parklab/files/scottouellette_0.jpeg?m=1445275612&itok=K51ECKii
    link: http://www.scott-ouellette.com/
    more_info: '<a href="http://compbio.hms.harvard.edu/" target="_blank">Park Lab</a>'

team_members_config:
  group_by_role: false # Not yet implemented
  show_emails: false

layout:

  # Imported from Google Fonts. If change, will likely need to adjust CSS for certain 
  # elements to find best-fitting font-weights ('bold-ness'), such as navs.
  header_font: Rubik
  body_font: Source Sans Pro

  # Depending on the font, normal font-weight (400) may appear too bold for the site's body font-size. May adjust it here.
  body_font_weight: 400
  body_font_bold_weight: 500

  # Nav sizes
  page_nav_height: 64
  page_nav_font_size: 15 # In pixels
  section_nav_height: 50
  section_nav_font_size: 13 # In pixels

  # Increase or decrease size of section dividers
  divider_size: 100