---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown
repo: cscb-template

### content configuration ###
title:       "Center for Stem Cell Bioinformatics | HMS DBMI"
keywords:    "Harvard, Medical, School, university, stem cell, bioinformatics"
description: "A single-page template for Jekyll based blogs (like what you'd use on github pages!)"
source_link: "https://github.com/t413/SinglePaged"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:        '#111111'
  white:        '#f8f8f8'
  blue:         '#49a7e9'
  bluedark:     '#3892d2'
  green:        '#9bcf2f'
  purple:       '#c869bf'
  orange:       '#fab125'
  turquoise:    '#0fbfcf'

kramdown:
  auto_ids:  false

# Setup pages
collections:
  home:
    order: 0
  about:
    order: 1
  team:
    order: 4